
name: Run Jmeter Tests from Config File
on:
  push:
    branches:
      - main


jobs:  
  job1-api:
    runs-on: ubuntu-latest
    strategy:
      matrix:
          folder: [a2000-legacy-app-2/folder-1]
    
    steps:
      # checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

    #  - name: Read and process lines from text file
     #   run: |
     #     while IFS= read -r line || [ -n "$line" ]; do
      #      # Split the line into components

     # - name: Set up AWS CLI
      #  uses: aws-actions/configure-aws-credentials@v1
       # with:
        #  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        #  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         # aws-region: us-east-1


      - name: Run Script
        run: |
          echo "Processing folder: ${{ matrix.folder }}"
          if [ -f "${{ matrix.folder }}/script10.sh" ]; then
            bash "${{ matrix.folder }}/script10.sh"
          else
            echo "No script found in ${{ matrix.folder }}"
          fi
  job2-ui:
    needs: job1-api
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder: [a2000-legacy-app-2/folder-2]
    
    steps:
      # checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Script
        run: |
          echo "Processing folder: ${{ matrix.folder }}"
          if [ -f "${{ matrix.folder }}/script11.sh" ]; then
            bash "${{ matrix.folder }}/script11.sh"
          else
            echo "No script found in ${{ matrix.folder }}"
          fi
  job3-api:
    needs: job2-ui
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder: [a2000-legacy-app-2/folder-3]
    
    steps:
      # checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Script
        run: |
          echo "Processing folder: ${{ matrix.folder }}"
          if [ -f "${{ matrix.folder }}/script12.sh" ]; then
            bash "${{ matrix.folder }}/script12.sh"
          else
            echo "No script found in ${{ matrix.folder }}"
          fi
