name: Multi-Component Workflow

on: 
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  # a2000-legacy-app-1 - DeterAPI1
  a2000-legacy-app-1-DeterAPI1:
    name: a2000-legacy-app-1 - DeterAPI1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Folder 1 Script a2000-legacy-app-1)
        working-directory: a2000-legacy-app-1/DeterAPI1
        run: |
          # Replace with your script command
          ./script1.sh
          ./script2.sh

  a2000-legacy-app-1-DeterUI:
    name: a2000-legacy-app-1 - DeterUI
    needs: a2000-legacy-app-1-DeterAPI1 # Ensure sequential execution
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Folder 2 Script (a2000-legacy-app-1)
        working-directory: a2000-legacy-app-1/DeterUI
        run: |
          # Replace with your script command
          ./script1.sh

  # Second Component - Component B
  componentB-folder1:
    name: Component B - Folder 1
    runs-on: windows-latest # Different runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Folder 1 Script (Component B)
        working-directory: componentB/folder1
        run: |
          # Replace with your script command
          .\your-script.ps1 # Example for PowerShell script

  componentB-folder2:
    name: Component B - Folder 2
    needs: componentB-folder1 # Ensure sequential execution
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Folder 2 Script (Component B)
        working-directory: componentB/folder2
        run: |
          # Replace with your script command
          .\your-script.ps1
