name: Multi-Component Workflow

on: 
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  # a2000-legacy-app-1 - DeterAPI1
  a2000-legacy-app-1-DeterAPI1:
    name: a2000-legacy-app-1 - DeterAPI1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run DeterAPI1 Script a2000-legacy-app-1)
        working-directory: a2000-legacy-app-1/DeterAPI1
        run: |
          # Replace with your script command
      - name: Run your script
          ./script1.sh
          ./script2.sh

  a2000-legacy-app-1-DeterUI:
    name: a2000-legacy-app-1 - DeterUI
    needs: a2000-legacy-app-1-DeterAPI1 # Ensure sequential execution
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run DeterUI Script (a2000-legacy-app-1)
        working-directory: a2000-legacy-app-1/DeterUI
        run: |
          # Replace with your script command
          ./script1.sh

  # Second Component - a2000-legacy-app-2
  a2000-legacy-app-2-folder1:
    name: a2000-legacy-app-2 - folder-1
    runs-on: windows-latest # Different runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run folder-1 Script (a2000-legacy-app-2)
        working-directory: a2000-legacy-app-2/folder-1
        run: |
          # Replace with your script command
          ./script10.sh # Example for PowerShell script

  a2000-legacy-app-2-folder-2:
    name: a2000-legacy-app-2 - folder-2
    needs: a2000-legacy-app-2-folder1 # Ensure sequential execution
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Folder 2 Script (a2000-legacy-app-2)
        working-directory: a2000-legacy-app-2/folder-2
        run: |
          # Replace with your script command
          ./script11.sh
