name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  call-reusable-workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Call Workflow for a2000-legacy-app-1
        uses: ./.github/workflows/a2000-legacy-app-1.yml
       
      - name: Call Workflow for a2000-legacy-app-2
        uses: ./.github/workflows/a2000-legacy-app-2.yml
