name: main workflow
on: 

  workflow_dispatch:
jobs:
  a2000-dete-app:
    if: ${{ github.event.inputs.a2000-dete-app1 == 'true'}}
    uses: ./.github/workflows/a2000-dete-app.yml
    with: 
        JmeterAPIscript1 : "DeterAPI/script1.sh"
